# Generated by Django 5.2.1 on 2025-06-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('Islands', 'Islands'), ('Tuen Mun', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Kwai Tsing', 'Kwai Tsing'), ('Tsuen Wan', 'Tsuen Wan'), ('North', 'North'), ('Tai Po', 'Tai Po'), ('Sha Tin', 'Sha Tin'), ('Sai Kung', 'Sai Kung'), ('Sham Shui Po', 'Sham Shui Po'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Eastern', 'Eastern'), ('Central and Western', 'Central and Western'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai')], max_length=50),
        ),
    ]
